// ProjectTile displays one project in a list.
// It holds a Project object and is generated by the ListView itemBuilder
//
import 'package:flutter/material.dart';

const _rowHeight = 60.0;
final BorderRadius _borderRadius = BorderRadius.circular(_rowHeight / 2);
const _aColor = Colors.yellow;

class ProjectTile extends StatelessWidget {
  // final Project project;
  final String displayString;
  final ValueChanged<String> onTap;
  final Color backgroundColor;

  ProjectTile(
      {Key key,
        @required this.displayString,
        @required this.backgroundColor,
        @required this.onTap})
      : assert(displayString != null),
        assert(onTap != null),
        super(key: key);

  @override
  Widget build(BuildContext context) {
    // Material
    // Container
    // InkWell
    // Padding
    // Row
    // Center
    return Material(
//      color: backgroundColor, //Colors.transparent,
      color: Colors.transparent ,//onTap == null ? Colors.orange : backgroundColor,

      child:
      // Container
      // InkWell
      // Padding
      // Row
      // Center
      Card(
        margin: EdgeInsets.all(6.0),
        color: backgroundColor,
        elevation: 2.0,
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8.0)),
        child: InkWell(
          borderRadius: _borderRadius,
          highlightColor: _aColor,
          splashColor: _aColor,
          onTap: () => onTap(displayString),
          child: Padding(
            padding: const EdgeInsets.all(8.0),
            child: Row(
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: [
                Center(
                  child: new Text(
                    displayString,
                    overflow: TextOverflow.ellipsis,
                    softWrap: false,
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
